theme: jekyll-theme-slate
title: simPM
description: SIMulation-based power analysis for Planned Missing designs
authors: Yi Feng & Gregory R. Hancock
show_downloads: true
markdown: kramdown
highlighter: rouge
